// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89yRz8yeJUBaenqWoMiJiI3HD2NRkW90',
    appId: '1:735659951006:web:7ca58ec2fae69d0c87cc8f',
    messagingSenderId: '735659951006',
    projectId: 'agenda-greed',
    authDomain: 'agenda-greed.firebaseapp.com',
    storageBucket: 'agenda-greed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh295LVd_iLksG4iIv2KalhdL5zbXQtng',
    appId: '1:735659951006:android:cba017821b273a9d87cc8f',
    messagingSenderId: '735659951006',
    projectId: 'agenda-greed',
    storageBucket: 'agenda-greed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpO7I1ykan5ZodSHMbDnf2JrHsAD1Drk',
    appId: '1:735659951006:ios:bd4c4cc4b21c4d2087cc8f',
    messagingSenderId: '735659951006',
    projectId: 'agenda-greed',
    storageBucket: 'agenda-greed.appspot.com',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMpO7I1ykan5ZodSHMbDnf2JrHsAD1Drk',
    appId: '1:735659951006:ios:a9d09d62719f8b3187cc8f',
    messagingSenderId: '735659951006',
    projectId: 'agenda-greed',
    storageBucket: 'agenda-greed.appspot.com',
    iosBundleId: 'com.example.agenda.RunnerTests',
  );
}
